# Schema for the configuration files of the Bootstrap Barrio Subtheme.

az_barrio.settings:
  type: theme_settings
  label: 'Arizona Barrio Subtheme settings'
  mapping:
    bootstrap_barrio_library:
      type: text
      label: 'Library'
    bootstrap_barrio_sidebar_position:
      type: text
      label: 'Sidebar Position'
    bootstrap_barrio_content_offset:
      type: integer
      label: 'Offset'
    bootstrap_barrio_sidebar_first_width:
      type: integer
      label: 'Width'
    bootstrap_barrio_sidebar_first_offset:
      type: integer
      label: 'Offset'
    bootstrap_barrio_sidebar_second_width:
      type: integer
      label: 'Width'
    bootstrap_barrio_sidebar_second_offset:
      type: integer
      label: 'Offset'
    bootstrap_barrio_footer_layout:
      type: text
      label: 'Layout'
    bootstrap_barrio_fluid_container:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_button:
      type: integer
      label: 'Convert submit to button'
    bootstrap_barrio_button_size:
      type: text
      label: 'Size'
    bootstrap_barrio_button_outline:
      type: integer
      label: 'Button outline'
    bootstrap_barrio_navbar_top_position:
      type: text
      label: 'Position'
    bootstrap_barrio_navbar_top_color:
      type: text
      label: 'Color'
    bootstrap_barrio_navbar_top_background:
      type: text
      label: 'Background'
    bootstrap_barrio_navbar_position:
      type: text
      label: 'Position'
    bootstrap_barrio_navbar_color:
      type: text
      label: 'Color'
    bootstrap_barrio_navbar_background:
      type: text
      label: 'Background'
    bootstrap_barrio_navbar_toggle:
      type: integer
      label: 'Enable'
    bootstrap_barrio_navbar_container:
      type: text
      label: 'Container'
    bootstrap_barrio_table_hover:
      type: integer
      label: 'Enable Table Hover'
    bootstrap_barrio_anchors_fix:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_anchors_smooth_scrolling:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_forms_required_has_error:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_forms_has_error_value_toggle:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_forms_smart_descriptions:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_forms_smart_descriptions_limit:
      type: integer
      label: 'Limit'
    bootstrap_barrio_forms_smart_descriptions_allowed_tags:
      type: text
      label: 'Allowed tags'
    bootstrap_barrio_popover_enabled:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_popover_animation:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_popover_html:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_popover_placement:
      type: text
      label: 'Placement'
    bootstrap_barrio_popover_selector:
      type: text
      label: 'Selector'
    bootstrap_barrio_popover_trigger_autoclose:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_popover_delay:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_popover_trigger:
      type: mapping
      mapping:
        hover:
          type: integer
          label: 'Hover'
    bootstrap_barrio_tooltip_enabled:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_tooltip_descriptions:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_tooltip_descriptions_length:
      type: integer
      label: 'Length'
    bootstrap_barrio_tooltip_animation:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_tooltip_html:
      type: integer
      label: 'Length'
    bootstrap_barrio_tooltip_delay:
      type: integer
      label: 'Enabled'
    bootstrap_barrio_popover_title:
      type: text
      label: 'Title'
    bootstrap_barrio_popover_content:
      type: text
      label: 'Content'
    bootstrap_barrio_tooltip_placement:
      type: text
      label: 'Placement'
    bootstrap_barrio_tooltip_container:
      type: text
      label: 'Container'
    bootstrap_barrio_tooltip_selector:
      type: text
      label: 'Selector'
    bootstrap_barrio_tooltip_trigger:
      type: mapping
      mapping:
        hover:
          type: text
          label: 'Hover'
    bootstrap_barrio_popover_container:
      type: text
      label: 'Container'
    bootstrap_barrio_region_clean_alert:
      type: integer
      label: 'Enable clean wrapper for alert region'
    bootstrap_barrio_region_class_alert:
      type: text
      label: 'Classes for alert region'
    bootstrap_barrio_region_clean_content_featured:
      type: integer
      label: 'Enable clean wrapper for content featured region'
    bootstrap_barrio_region_class_content_featured:
      type: text
      label: 'Classes for content featured region'
    bootstrap_barrio_region_clean_full_width_content_bottom:
      type: integer
      label: 'Enable clean wrapper for content bottom region'
    bootstrap_barrio_region_class_full_width_content_bottom:
      type: text
      label: 'Classes for content bottom region'
    bootstrap_barrio_region_clean_footer:
      type: integer
      label: 'Enable clean wrapper for footer region'
    bootstrap_barrio_region_class_footer:
      type: text
      label: 'Classes for footer region'
    bootstrap_barrio_region_clean_footer_sub:
      type: integer
      label: 'Enable clean wrapper for footer sub region'
    bootstrap_barrio_region_class_footer_sub:
      type: text
      label: 'Classes for footer sub region'
    wordmark:
      type: boolean
      label: 'Enable wordmark logo'
    az_main_menu_style:
      type: string
      label: 'Main menu style'
    az_bs_overlay_menu_scroll:
      type: boolean
      label: 'Enable overlay menu scroll'
    info_security_privacy:
      type: boolean
      label: 'Enable privacy link'
    copyright_notice:
      type: text
      label: 'Copyright notice'
    az_hide_front_title:
      type: boolean
      label: 'Enable hide front page title'
    az_back_to_top:
      type: boolean
      label: 'Enable ''Back to Top'' button'
    az_bootstrap_source:
      type: string
      label: 'AZ Bootstrap source'
    az_bootstrap_cdn_version:
      type: string
      label: 'AZ Bootstrap CDN version'
    az_bootstrap_minified:
      type: boolean
      label: 'Enable AZ Bootstrap minification'
    az_barrio_font:
      type: boolean
      label: 'Use the centrally-managed Typekit webfont, Proxima Nova'
    az_barrio_material_design_sharp_icons:
      type: boolean
      label: 'Use Material Design Sharp Icons'
    az_barrio_az_icons:
      type: boolean
      label: 'Use AZ Icons'
    az_barrio_az_icons_source:
      type: string
      label: 'AZ Icons source'
    sticky_footer:
      type: boolean
      label: 'Enable AZ Bootstrap sticky footer template'
    az_barrio_logo_svg_inline:
      type: boolean
      label: 'Inline logo SVG (Experimental)'
    az_barrio_footer_logo_svg_inline:
      type: boolean
      label: 'Inline footer logo SVG (Experimental)'
    primary_logo_alt_text:
      type: string
      label: 'Primary logo alt text'
    primary_logo_title_text:
      type: string
      label: 'Primary logo title text'
    footer_logo_link_destination:
      type: string
      label: 'Footer logo link destination'
    footer_logo_alt_text:
      type: string
      label: 'Footer logo alt text'
    footer_logo_title_text:
      type: string
      label: 'Footer logo title text'
    footer_logo_path:
      type: path
      label: 'Footer logo path'
