az_publication.type.*:
  type: config_entity
  label: 'Quickstart Publication Type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    type:
      type: string
      label: 'Mapped type'
    uuid:
      type: uuid
      label: 'Universally Unique Identifier'
