az_cas.settings:
  type: config_object
  label: 'AZ CAS settings'
  mapping:
    disable_login_form:
      type: boolean
      label: 'Disable login form'
    disable_admin_add_user_button:
      type: boolean
      label: 'Disable button for adding non-CAS users in admin interface'
    disable_password_recovery_link:
      type: boolean
      label: 'Disable password recovery link'
    guest_mode:
      type: boolean
      label: 'Enable guest authentication mode'