views.filter_value.az_event_trellis_views_date_filter:
  type: views_filter
  label: 'Trellis filter'
  mapping:
    value:
      type: string
      label: 'Value'
    begin:
      type: string
      label: 'Custom Date Range Begin'
    end:
      type: string
      label: 'Custom Date Range End'
az_event_trellis.az_recurring_import_rule.*:
  type: config_entity
  label: Trellis Event Import
  mapping:
    id:
      type: machine_name
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    host:
      type: string
    owner:
      type: string
    keyword:
      type: string
    attributes:
      type: sequence
      label: ‘Enterprise Attributes’
      sequence:
        type: string
        label: ‘Attribute’
    approval:
      type: string
