debug: false
staging: false
allow_embedding: false
login_url: assets.arizona.edu
login_enable_browser_login: true
login_enable_custom_url: true
dependencies:
  enforced:
    module:
      - az_digital_asset_library
